manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-ardux
      url-base: https://github.com/arduxio
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 6f85f48b19afae04f98e9abacb36ce1425b61f78
      import: app/west.yml
  self:
    path: config
